### ISSUE TITLE
using "options.domain" causes some problems in request

### ISSUE THREAD

**Issue by FrankyBoy** [colynb/request-ntlm#4]
You get some nice error message starting like so...

```
events.js:86
    this.domain.enter();
                ^
TypeError: Object yourDomain has no method 'enter'
    at Request.emit (events.js:86:17)
    at IncomingMessage.<anonymous> (D:\git\bwin-bcm-bindings\bwin-bcm-bindings\node_modules\request\request.js:1108:12)
```

suggestion would be to rename "domain" to "ntlm_domain" to avoid this collision. Will provide patch asap.

**Comment by bignis** [comment]
This appears to be directly related to https://github.com/joyent/node/issues/3922
